[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"

[theme.sidebar]
primaryColor = "#FF4B4B"
backgroundColor = "#262730"
secondaryBackgroundColor = "#0E1117"
textColor = "#FAFAFA"
borderColor = "#464B5C"
showWidgetBorder = true
